apiVersion: v1
kind: Service
metadata: 
  name: medilab-boot-db-service
  labels:
    app: medilab-boot-db
  namespace: database-ns

spec:
  #type: NodePort      
  selector:
    app: medilab-boot-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
